### ISSUE TITLE
 torch.load(pruned_model)

### ISSUE THREAD

**Issue by wuzhiyang2016** [eeric/channel_prune#10]
when i use torch.load() to load pruned model , error happened: AttributeError: 'module' object has no attribute 'ModifiedVGG16Model', anyone meet this problem?

**Comment by eeric** [comment]
@wuzhiyang2016 ,
it is basic problem, it means no define for model pruned, and didn't knowed ModifiedVGG16Model.

**Comment by wuzhiyang2016** [comment]
thanks, but how we can use pruned model?  just save the values of params, and recode each conv layer's channel, then reconstruct  the net's architect?

**Comment by wuzhiyang2016** [comment]
I solved it , I declare the class ModifiedVGG16Model() before the torch.load(),  it works
