### ISSUE TITLE
Residual connection in prunner

### ISSUE THREAD

**Issue by ShirelJosef** [eeric/channel_prune#11]
in function "forward" in the class "FilterPrunner" there is no residual connection in the blocks of layers 4,5,6,7 as suppose to be in resent. why?
Thanks

**Comment by milulee** [comment]
I have the same question, and there is no 'downsample' in the forward, do you know why?

**Comment by milulee** [comment]
> I have the same question, and there is no 'upsample' in the forward, do you know why?

sorry, I mean 'downsample'.
there is no 'downsample' and shortcut in the forward, can you tell me why? thank you very mach

**Comment by eeric** [comment]
@milulee,@ShirelJosef
you debuged  fine_tuner.prune()  on the 360th line in finetune.py, and then debug def prune(self): on the 278th line in finetune.py.

**Comment by kunalgoyal9** [comment]
@milulee  @ShirelJosef did you get?

**Comment by kunalgoyal9** [comment]
I have solved those issues and raised a pull request. But I don't think it will be merged anyway.
