### ISSUE TITLE
 where is the prune_conv_layer??

### ISSUE THREAD

**Issue by cvJie** [eeric/channel_prune#12]
oh ,sorry ,i can’t found the prune_conv_layer function in the prune.py 262 line.

the code block is:
  if __name__ == '__main__':
	model = models.vgg16(pretrained=True)
	model.train()

	t0 = time.time()
	model = prune_conv_layer(model, 28, 10).  # the function no found 
	print("The prunning took", time.time() - t0)

**Comment by eeric** [comment]
@cvJie 
oh,  prune_resnet18_conv_layer replaced it.
