### ISSUE TITLE
Hello, I get this error while running，How do I solve it.

### ISSUE THREAD

**Issue by vaeXu** [eeric/channel_prune#2]
Traceback (most recent call last):
  File "finetune.py", line 375, in <module>
    fine_tuner.train(epoches=10)
  File "finetune.py", line 218, in train
    self.train_epoch(optimizer)
  File "finetune.py", line 238, in train_epoch
    self.train_batch(optimizer, batch.cuda(), label.cuda(), rank_filters)
  File "finetune.py", line 233, in train_batch
    self.criterion(self.prunner.model_forward(input), Variable(label)).backward()
  File "finetune.py", line 147, in model_forward
    x = self.model.features._modules.items()[layer][1][kt].conv1(x)
TypeError: 'odict_items' object does not support indexing

**Comment by eeric** [comment]
@GAVANXU 
x = self.model.features._modules.items()[layer][1][kt].conv1(x)
it was error to self.model.features._modules.items(), you needed try on self.model._modules.items() by debugging step by step.

**Comment by TheLostIn** [comment]
Hello,I've solve this problem by change it into `x = self.model.features._modules.get(str(layer))[kt].bn1(x)`.
