### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by ssxlconch** [eeric/channel_prune#3]
Traceback (most recent call last):
  File "/home/wade/Downloads/finetune-res.py", line 351, in <module>
    print model
NameError: name 'model' is not defined

**Comment by eeric** [comment]
model didn't exist or model wasn't be loaded

**Comment by ssxlconch** [comment]
before i run the code by python finetune.py, which model should i download?

**Comment by ssxlconch** [comment]
@eeric 
Thanks for reply, I solve the problem 
but when I run python finetune-res.py --train
my output accuracy is always %
  )
)
Epoch:  0
Accuracy : 100.0%
Epoch:  1
Accuracy : 100.0%
Epoch:  2
Accuracy : 100.0%
Epoch:  3
Accuracy : 100.0%
Epoch:  4

Can you help me to solve the problem?

**Comment by eeric** [comment]
model migntn't be pruned, you could debug by sentense that python -m pdb finetune-res.py --train

**Comment by ssxlconch** [comment]
@eeric thank you for reply, I had solve the problem

**Comment by tearhupo121031** [comment]
Hi,which dataset you use in this experiment? I download CIFAR10 on kaggle, the testset is 6x more than trainset, the accuracy is always 0,I change the number of picture in testset, the accuracy release to 60%…do you have any dataset?

**Comment by ssxlconch** [comment]
@eeric Hi,I'm sorry to bother you again,could you please tell me which dataset you had used in this experiment? I download CIFAR10 on kaggle, the testset(300000) is 6x more than trainset(50000), the accuracy is always 1,I change the number of picture in testset to 20000, the accuracy release to 60%…

**Comment by eeric** [comment]
check your test code by script:  python -m pdb
