### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by jingdonglin** [eeric/channel_prune#5]
hellow,eeric   ,when I run the  command ,there  are  always so many errors...like this:
File "finetune.py", line 27
    model = nn.Sequential(*modules)
                                  ^
TabError: inconsistent use of tabs and spaces in indentation.
so ,how to solve it?
     thanks for your reply

**Comment by eeric** [comment]
please learn python usage.

**Comment by kunalgoyal9** [comment]
this is very serious error in your code
