### ISSUE TITLE
What's your plan to prune by one pass

### ISSUE THREAD

**Issue by NokiaDDT** [eeric/channel_prune#8]
Hi, @eeric,

Thanks for your great work. I saw you say that in principle the pruning process could be done in one pass, do you have any plan to do this? Maybe you would provide some idea or pseudo code, thanks.

**Comment by eeric** [comment]
Ok, pruning was an effective method for sample model design , on the contrary produced little effect
 for complicated model that had many convs and some block etc.
At present, I didn't develop pruning.

**Comment by NokiaDDT** [comment]
I see, thanks for your reply. Why just little effect for complicated model? Because spend too much time to prune and improve less? Any other way for model compression?
B.R.

**Comment by eeric** [comment]
I didn't know too many reasons, except for the results of the experiment.

**Comment by NokiaDDT** [comment]
Thanks :)
