### ISSUE TITLE
low accuracy(57%) before prunning, but high accuracy(95%) after prunning

### ISSUE THREAD

**Issue by CF2220160244** [eeric/channel_prune#9]
hi @eeric , i run your code, and i have this question:
i run 10 epochs ang get accuracy of 57% before  prunning, but after prunning i can get accuracy of 95%! can you explain this?

**Comment by eeric** [comment]
congratulation!

**Comment by CF2220160244** [comment]
@eeric Thank you for your excellent code, by the way, i want to know why the accuracy(57%) is so small? What‘s your accuracy before prunning, Did you get a high accuracy before prunning?

**Comment by eeric** [comment]
to my model prunned, it was lower than original by 1.5% for accuracy.

**Comment by CF2220160244** [comment]
@eeric maybe i think the ICLR2019 work(RETHINKING THE V ALUE OF N ETWORK P RUNING) can explain my puzzle, according to this paper: starting with training a large, over-parameterized network is not necessary, a high-performance model before prunning is not necessary.

**Comment by eeric** [comment]
ok, maybe it was not excellent to your original model.

**Comment by CF2220160244** [comment]
@eeric  when i read you code, when rank_filters=False,        
 i can't understand why you train with:
        self.criterion(self.prunner.model_forward(input), Variable(label)).backward()
rather than:
        self.prunner.model_forward(input)
can you help me? if you are a chinese, you can answer me to 2220160244@bit.edu.cn using chinese  conveniently. thank you very much.

**Comment by CF2220160244** [comment]
@eeric, i have 2 questions,
1. when training before you prune, i can't understand why you use: 
       self.prunner.model_forward(input)
rather than :
       self.model(input)
if use:     self.prunner.model_forward(input),     i think this is not the real resnet18 and the train accuracy is 57% before prune, so i think we should use :
       self.model(input)
2. when i use:  self.model(input) ,  the train accuracy is 98% before prune, but i can't prune and have this problem:
Filters prunned 86.88524590163935%
Traceback (most recent call last):
  File "finetune1.py", line 437, in <module>
    fine_tuner.prune()
  File "finetune1.py", line 394, in prune
    self.test()
  File "finetune1.py", line 213, in test
    output = self.model(Variable(batch))
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "finetune1.py", line 51, in forward
    x = self.features(x)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenfei/anaconda3/lib/python3.6/site-packages/torchvision/models/resnet.py", line 51, in forward
    out += residual
RuntimeError: The expanded size of the tensor (59) must match the existing size (42) at non-singleton dimension 1
 
can you help me? you can also answer me to 2220160244@bit.edu.cn using Chinese conveniently. thank you very much!

**Comment by CF2220160244** [comment]
1

**Comment by eeric** [comment]
@CF2220160244, input tensor size did not match in residual module.

**Comment by eeric** [comment]
@CF2220160244, tensor size did not match in residual module.

**Comment by CF2220160244** [comment]
1

**Comment by CF2220160244** [comment]
@eeric yes, but i don't know how to modify it, do you know how to modify i or can you give me some advice? thanks!

**Comment by eeric** [comment]
@CF2220160244, 1st, output channels of last conv equalled to input next conv,  2nd, ensured tensor size right in self.forward.

**Comment by eeric** [comment]
@CF2220160244 , 1st, output channels of last conv equalled to input next conv, 2nd, ensured tensor size right in self.forward.

**Comment by eeric** [comment]
@CF2220160244 
1st, output channels of last conv equalled to input next conv, 2nd, ensured tensor size right in self.forward.

**Comment by CF2220160244** [comment]
ok, I try it, thanks!

**Comment by massonh** [comment]
Hi @eeric ,

Thanks for the code but your forward passes (ranking, training and testing) aren't using the residual part of the model. Also when pruning conv2 in the blocs, you're changing the output's dimension which creates an add error when the residual part is added in the forward pass. In order to correct this problem, we need to avoid pruning the last layer of every convolutional block. For example, you could use a function similar to this one in order to determine if the layer can be pruned or not. 

def keep_layer_ranking(layer_index):
    pt = layer_index % 2
    if layer_index > 0 and pt == 0:
        return False
    else:
        return True
If false, we can't pruned the filter since the residual dimension will change. An alternative would also be to avoid computing the values for the filters in the last layer of every block. 

This residual part is very useful if we want to use the pretrained network on imagenet and get the accuracy specified by torchvision. By removing the residual part from the forward pass, we are also exposing the model to exploding gradients while training.

**Comment by CF2220160244** [comment]
i also find this question@massonh

**Comment by eeric** [comment]
@massonh, thanks for your advice, let me think.

**Comment by CF2220160244** [comment]
After changing the foward function, i get the right prune of the  resnet.

**Comment by eeric** [comment]
good, congratulations!

**Comment by shaliu2018** [comment]
>           After changing the foward function, i get the right prune of the  resnet.

Could you please tell me how you changed the foward function and how you solve the problem because i've juest met the same problem you met? @CF2220160244

**Comment by hongzhenwang** [comment]
@CF2220160244 @shaliu2018  +1, meet the same problem, 925369899@qq.com

**Comment by hongzhenwang** [comment]
Solved. training configuration is not right. change finetune.py line 29 and line 207

**Comment by kunalgoyal9** [comment]
we can add downsample block in every block and can change the output dimension of each respectively
